# This is a Logstash generated Gemfile.
# If you modify this file manually all comments and formatting will be lost.

source "https://rubygems.org"
gem "logstash-core"
gem "logstash-codec-json"
gem "logstash-codec-rubydebug"
gem "logstash-input-generator"
gem "logstash-input-stdin"
gem "logstash-input-tcp"
gem "logstash-input-file"
gem "logstash-input-sqs"
gem "logstash-input-s3"
gem "logstash-filter-clone"
gem "logstash-filter-mutate"
gem "logstash-filter-json"
gem "logstash-filter-drop"
gem "logstash-filter-date"
gem "logstash-output-stdout"
gem "logstash-output-s3"
gem "logstash-output-elasticsearch"
gem "logstash-output-sqs", "0.1.3", :path => "vendor/local_gems/c58b399d/logstash-output-sqs-0.1.3"
